# Generated by Django 3.0.8 on 2020-07-28 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200728_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='wtl', to=settings.AUTH_USER_MODEL),
        ),
    ]
