# Generated by Django 3.0.8 on 2020-07-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200728_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='title',
        ),
        migrations.AddField(
            model_name='watch',
            name='listingid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='watch',
            name='user',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
