# Generated by Django 3.0.8 on 2020-07-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200730_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alllisting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=64)),
                ('description', models.CharField(default='', max_length=264)),
                ('link', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
        ),
    ]
