# Generated by Django 3.0.8 on 2020-07-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_delete_alllisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='comment',
            name='listing_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(default='', max_length=64),
        ),
    ]
