# Generated by Django 3.0.8 on 2020-08-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200731_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Electronic', 'Electronics'), ('Cloth', 'Cloth'), ('Shoes', 'Shoes')], default='', max_length=64),
        ),
    ]
