# Generated by Django 3.0.8 on 2020-08-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200802_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='status',
        ),
        migrations.AlterField(
            model_name='listing',
            name='wlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='list', to='auctions.Watch'),
        ),
    ]
